### ISSUE TITLE
Interoperability with Noise

### ISSUE THREAD

**Issue by solardiz** [LoupVaillant/Monocypher-Handshake#3]
To what extent is Monocypher-Handshake compatible with third-party implementations of Noise proper, has this been tested, and against which implementations, for what handshake patterns, etc? Thanks!

**Comment by LoupVaillant** [comment]
Oh, crap, this project is deprecated. I'm working on [Monokex](https://github.com/LoupVaillant/Monokex) now. I'll delete this repository shortly, sorry about the loss of time.

As for compatibility with Noise, there is none. It is a Noise _like_ key exchange, not a proper Noise implementation. Reason being (and I've more or less confirmed it with Monokex), Noise is still a bit more complex and a bit slower than it absolutely needs to be (see [Disco](https://www.youtube.com/watch?v=l7xV5z1eJLw) about simplicity). I may in the future implement actual Noise handshakes.

Note one thing about Monokex: it has a version that uses [Elligator](https://elligator.org) to obfuscate ephemeral keys and reduce the entire key exchange to a fully random stream of bytes. You could consider that an advantage over Noise.

Finally, Monokex is in a verification stage. It is _probably_ safe to use at the moment, and API and wire protocol are _probably_ stable, but I cannot make strong promises before I'm done analysing everything (though an audit of a previous version by Nadim Kobeissi, Noise Explorer author, was reassuring —he found no critical errors, only room for simplification).

**Comment by solardiz** [comment]
Thanks for the prompt response. I suggest you don't delete this repo - maybe edit its `README.md` and archive it, but not delete.

I also saw Monokex, and thought you were perhaps using its OCaml programs to generate the C code in here. No?

If Monokex is meant to replace this, then I think it should somehow be made usable without an OCaml compiler. Include a subdirectory with pre-generated C code?

**Comment by LoupVaillant** [comment]
> I suggest you don't delete this repo - maybe edit its README.md and archive it, but not delete.

I’ll consider it, but I confess I don’t like the redundancy with Monokex.

> I also saw Monokex, and thought you were perhaps using its OCaml programs to generate the C code in here. No?

Now that you mention it, I used to. But I stopped somewhere along the line, now that the OCaml program is able to generate a full implementation with its own test suite.

> If Monokex is meant to replace this, then I think it should somehow be made usable without an OCaml compiler.

I do intend to release the generated code as such at some point. I’m also thinking of maybe rewrite the code generator in C, though it’s not a priority.
